export interface EmpresaRequestDTO {
    idEmpresa?: number,
    idTipoPersona: number | string,
    idRegimenContribuyente: number | string,
    idMunicipio: number | string,
    nitEmpresa: string,
    digitoVerificacionEmpresa: string,
    nombreEmpresa: string,
    razonSocialEmpresa: string,
    direccionEmpresa: string,
    codigoPostalEmpresa: string,
    telefonoEmpresa: string,
    correoEmpresa: string,
    logoEmpresa: string,
    estadoEmpresa: boolean | string,
    idDepartamento?: number | string,
}