export interface TerceroRequestEmpresaDTO {
    idTercero?: number,
    idEmpresa: number | string,
    idTipoPersona: number | string,
    idMunicipio: number | string,
    idDepartamento?: number | string,
    idRegimenContribuyente: number | string,
    nitTercero: string,
    digitoVerificacionTercero: string,
    razonSocialTercero: string,
    nombreTercero: string,
    telefonoTercero: string,
    direccionTercero: string,
    correoTercero: string,
    codigoPostalTercero: string,
    proveedorTercero?: boolean,
    estadoTercero: boolean | string,
}