export interface UsuarioRequestDTO {
    idUsuario?: number,
    idEmpresa: number | string,
    idTipoDocumento: number | string,
    idMunicipio: number | string,
    idDepartamento?: number | string,
    idRol: number | string,
    numeroDocumentoUsuario: string,
    nombreUsuario: string,
    apellidoUsuario: string,
    correoUsuario: string,
    telefonoUsuario: string,
    direccionUsuario: string,
    claveUsuario: string,
    estadoUsuario: boolean | string,
    confirmarClaveUsuario?: string,
    claveNuevaUsuario?: string,
}